version: "3.9"

services:
  database:
    image: mysql
    container_name: conclusion-mysql
    hostname: mysql
    ports:
      - "6033:3306"
    environment:
      MYSQL_DATABASE: "conclusion-db"
      MYSQL_ROOT_PASSWORD: "mysql"
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql

  server:
    build: ./Dockerfile.server
    image: conclusion-server
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

volumes:
  mysql:
