version: "3.9"

services:
  database:
    image: mysql
    container_name: chunktube-db
    environment:
      MYSQL_DATABASE: "chunktube-db"
      MYSQL_ROOT_PASSWORD: "mysql"
    hostname: mysql
    ports:
      - "6033:3306"
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
