version: "3.9"

services:
  postgres:
    image: postgres
    container_name: conclusion-postgres
    hostname: postgres
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "conclusion-db"
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

  server:
    build: ./Dockerfile.server
    image: conclusion-server
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

volumes:
  postgres:
